export const DETECTIVE_ROOM_TEXTURES = [
    '/textures/vintage_clear_plywood.jpg',
    '/textures/clear_metal.jpg',
    '/textures/ceramic_white.jpg',
    '/textures/cork.jpg',
    '/textures/felt_beige.jpg',
    '/textures/fabric_leather_brown.jpg',
    '/textures/leather_white.jpg',
    '/textures/paper_collages_whites.jpg',
    '/textures/clock.jpg',
    '/textures/ceramic.jpg',
    '/textures/dirt.jpg',
    '/textures/bamboo.jpg',
    '/textures/leaf_bamboo.jpg',
    '/textures/cardboard.jpg',
    '/textures/stainless_steel.jpg',
    '/textures/cigar_wrapper.jpg',
    '/textures/burning_ash.jpg',
    '/textures/gold_foil.jpg',
    '/textures/dark_planks.jpg',
    '/textures/wallpaper_red.jpg',
    '/textures/written_letter.jpg',
    '/textures/globe_earth.jpg',
    '/textures/top_secret.jpg',
    '/textures/testimage.jpg',
    '/textures/mug_side.jpg',
    '/textures/mug_inside.jpg',
    '/textures/mug_bottom_inner.jpg',
    '/textures/mug_bottom.jpg',
    '/textures/aldi.jpg',
    '/textures/coffee_paper.jpg',
    '/textures/fontys.jpg',
    '/textures/initial_profile.jpg',
    '/textures/jfc.jpg',
    '/textures/notable_activity.jpg',
    '/textures/puzzle_work_experience.jpg',
    '/textures/studentaanhuis.jpg,',
    '/textures/tabletoptunes2.jpg',

    // From FlatDecorationCluster
    '/textures/the_place.jpg',
    '/textures/calender2025.jpg',
    '/textures/newspapers.jpg',

    // From WallsCluster
    '/textures/light_concrete.jpg',
    '/textures/cityscape.jpg',

    // From RedStringsEffect
    '/textures/basket_weave.jpg',

    // Extra files present in /textures (preload now, safe for future use)
    '/textures/cardboard_clean.jpg',
    '/textures/house_szn1.jpg',
    '/textures/wallpaper_beigbrown.jpg',
] as const